export const GET_ALL_CHECKLIST_REQUEST = "GET_ALL_CHECKLIST_REQUEST";
export const GET_ALL_CHECKLIST_SUCCESS = "GET_ALL_CHECKLIST_SUCCESS";
export const GET_ALL_CHECKLIST_FAILURE = "GET_ALL_CHECKLIST_FAILURE";

export const CREATE_CHECKLIST_REQUEST = "CREATE_CHECKLIST_REQUEST";
export const CREATE_CHECKLIST_SUCCESS = "CREATE_CHECKLIST_SUCCESS";
export const CREATE_CHECKLIST_FAILURE = "CREATE_CHECKLIST_FAILURE";

export const DELETE_CHECKLIST_REQUEST = "DELETE_CHECKLIST_REQUEST";
export const DELETE_CHECKLIST_SUCCESS = "DELETE_CHECKLIST_SUCCESS";
export const DELETE_CHECKLIST_FAILURE = "DELETE_CHECKLIST_FAILURE";
